### ISSUE TITLE
看不懂这东西怎么用啊，你这个客户端，我看不懂哪里添加vmss

### ISSUE THREAD

**Issue by An-spectator** [InfernalAzazel/gostx#1]

**Comment by InfernalAzazel** [comment]
gost  貌似不支持 vmss， 你可以试试 https 很稳定我用了一年多。下面客户端使用教程。

[如何搭建 gost 机场](https://github.com/haoel/haoel.github.io)

[gost 下载](https://github.com/ginuerzh/gost/releases) 

[gost 使用说明书](https://v2.gost.run/getting-started/)

![1](https://github.com/InfernalAzazel/gostx/assets/40333954/1bea2c55-6ccc-4e83-be1d-812fa34a6138)


![2](https://github.com/InfernalAzazel/gostx/assets/40333954/18bb98ef-0eb7-4c91-b0f8-6a2edfb5263a)

例如: 

![2](https://github.com/InfernalAzazel/gostx/assets/40333954/a9aa9d0d-9ef1-470e-b572-6cbf0b5e2b5f)

LINUX MAC Windows 都需要手动设置代理

Linux 系统设置如下:

settings -> network -> network proxy

![4](https://github.com/InfernalAzazel/gostx/assets/40333954/13ff0703-b15c-4cd4-a835-32fd7ffdd255)
